### ISSUE TITLE
Create support libraries for OpalKelly's FrontPanel APIs

### ISSUE THREAD

**Issue by silicondosa** [usc-bbdl/R01v2#3]
Create a libraries directory with okFrontPanel compiled libraries. Suggest moving all other libraries to the same directory as well.

**Comment by briancohn** [comment]
is this pre- sep1 or post sep1?

**Comment by silicondosa** [comment]
This needs come be fixed by sep 1

Regards,

Suraj Chakravarthi Raja
Doctoral Student
Ming Hsieh Department of Electrical Engineering
USC Viterbi School of Engineering

**Comment by silicondosa** [comment]
Created a 'lib' directory with the okFrontPanel library inside.
We must consider using this library for all things that are libraries.
